version: "3.2"
services:
  owntracks-omlox:
    image: wetzelbe/owntracks-omlox:latest
    restart: "unless-stopped"
    networks: 
      - deephub-net
    environment: 
      - OMLOX_HOSTNAME=8081-deephub-apache
      - OMLOX_PATH_PREFIX=/deephub
      - OMLOX_PORT=80
      - MQTT_HOSTNAME=mqtt
  mqtt:
    image: eclipse-mosquitto
    restart: "unless-stopped"
    networks: 
      - deephub-net
    ports: 
      - "1883:1883"
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
networks:
  deephub-net:
